### ISSUE TITLE
Integrate DoppelData and EHR layers

### ISSUE THREAD

**Issue by jenniferjiangkells** [dotimplement/HealthChain#10]
## TODOs

@adamkells 
- [x] Create mapping list of user options (problems, duration of stay, medications...) to FHIR resources.
- [x] Create big daddy .generate() method that validates input, creates all resources requested and updates it according to complexity specification.
- [x] Create method for loading in user json data.

@jenniferjiangkells 
- [x] Create list of codes for complexity levels for each option (healthy, simple, complex)
- [x] Create Use Case specific wrapper method that also creates synthetic meta-data required by API request.
- [x] Create methods for saving request and response data.
- [x] Replace placeholders elsewhere in the code to the new data generator signatures.
