### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by jenniferjiangkells** [dotimplement/HealthChain#11]
## TODOs

- [ ] Introduction / purpose statement / tagline
- [ ] Quickstart in README
- [ ] Set up Docs page
- [ ] Basic Concepts: CDS, FHIR
- [ ] Document `sandbox`, `ehr`, `api` decorators
- [ ] Document `DataGenerator` @adamkells 
- [ ] Add example code snippet
- [ ] Add license, contribution guidelines
- [ ] Add logo
